### ISSUE TITLE
DOS line endings on Python code

### ISSUE THREAD

**Issue by tazle** [fdenivac/Lightroom-SQL-tools#1]
All the Python files in this repository have DOS line endings ('\r\n'), which makes the project difficult to use on Mac and Linux.

Git has options to automatically convert line endings to match the local system, but I suppose that requires some configuration that is not present.

**Comment by fdenivac** [comment]
Fixed following this github page : https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings.
Thanks you for this.
