### ISSUE TITLE
Sort with Custom Order from Lightroom

### ISSUE THREAD

**Issue by Rotbarde** [fdenivac/Lightroom-SQL-tools#4]
I find the database tool very useful. However, I still have a few problems with certain criteria. I would like to output Publish Collections. With this command I can filter exactly the publish collection with the exact name (e.g. (ARM-1001): 

`lrselect.py "pubcollection, name=base" "pubcollection=ARM-1001, name=%" -r`

```
 * Photo results (10 photos) :
                     pubcollection | name
    =====================================================
                          ARM-1001 | makramee-armband-mit-baum-metallverbinder-gruen-arm-1001-87-086
                          ARM-1001 | makramee-armband-mit-baum-metallverbinder-arm-1001-067
                          ARM-1001 | makramee-armband-mit-baum-metallverbinder-arm-1001-130
                          ARM-1001 | makramee-armband-mit-baum-metallverbinder-blau-arm-1001-275-044
                          ARM-1001 | makramee-armband-mit-baum-metallverbinder-lila-arm-1001-369-106
                          ARM-1001 | makramee-armband-mit-baum-metallverbinder-arm-1001-081
                          ARM-1001 | makramee-armband-mit-baum-metallverbinder-blau-arm-1001-275-092
                          ARM-1001 | makramee-armband-mit-baum-metallverbinder-rot-arm-1001-44-094
                          ARM-1001 | makramee-armband-mit-baum-metallverbinder-gelb-arm-1001-274-103
                          ARM-1001 | makramee-armband-mit-baum-metallverbinder-lila-arm-1001-369-088
```

If I work with jokers (ARM%), however, nothing is displayed, e.g. 

`lrselect.py "pubcollection, name=base" "pubcollection=ARM%, name=%" -r`

What is the reason for this?

And is it possible to set the sorting so that it shows me exactly the custom order from Lightroom, just as I have arranged the photos in the publishing folder independently?
Unfortunately, the order of the photos in the output does not correspond to the custom order from Lightroom

**Comment by fdenivac** [comment]
Hi,
Note first that in criteria,  "name=%"  is correct but not usefull.

1.  **Fixing pubcollection joker** :

    You can see your problem using argument "--sql" for display the final SQL query :
 
```  
lrselect.py "pubcollection, name=base" "pubcollection=ARM%" --sql
 * SQL request =  SELECT  pc.name AS pubcollection, fi.baseName AS name FROM Adobe_images i LEFT JOIN AgLibraryPublishedCollectionImage pci ON p
ci.image = i.id_local LEFT JOIN AgLibraryPublishedCollection pc ON pc.id_local = pci.collection LEFT JOIN AgLibraryFile fi ON i.rootFile = fi.id
_local WHERE (i.id_local = pci.image AND pc.name = "ARM%" COLLATE NOCASE)
```
So, the fix in ` lrselectphoto.py` is : 
```>/cygdrive/c/Lightroom> grep -n "pc.name = " lrtools/*.py
lrtools/lrselectphoto.py:520:        return f'(i.id_local = pci.image AND pc.name LIKE "{value}" COLLATE NOCASE)'
lrtools/lrselectphoto.py:528:        return f'(i.id_local = pci.image AND pc.name LIKE "{value}" COLLATE NOCASE)'
```


2. **Sorting by custom order**
Fixed with introducing a new column ''`pubposition`".
So, your request is now :
`lrselect.py "pubcollection, name=base, pubposition" "pubcollection=ARM%, sort=pubposition" -r`
Giving something as :
```
lrselect.py "pubcollection, name=base, pubposition" "pubcollection=TEST%,sort=-pubposition" -r
 * Photo results (6 photos) :
                     pubcollection | name                 | pubpos
    ==============================================================
                   TestPublication | D7K_57807            |   0.25
                   TestPublication | D7K_28541            |    0.5
                   TestPublication | RX100_02513          |   2.75
                   TestPublication | D7K_31689            |    3.5
                   TestPublication | D7K_40017            |    5.0
                   TestPublication | D80_41517            |    6.0
```
The _sort_ criteria here, can be "sort=pubposition",  "sort=-pubposition", "sort=3", "sort=-3"

Test the project updated, and let me know if you have any problems

**Comment by Rotbarde** [comment]
Hi.
Works great, thanks for the change. I can now use this command for output all collections:

`lrselect.py "pubcollection, name=base, pubposition" "pubcollection=%, sort=-3" -r -N --raw_print > export.csv`

The only thing I have noticed. When I change the custom order in Lightroom and Lightroom is open, it takes some time for the change to appear in the database. This means that as soon as I close Lightroom, the changed order is displayed instantly. Is this because Lightroom first writes the cache and then transfers the change to the database when Lightroom is closed? Can I somehow bypass the cache while Lightroom is open?

**Comment by fdenivac** [comment]
Unfortunately, I don't have any specific information about the internal workings of Lightroom regarding the database.
But I actually notice that writing in sqlite is not immediate: it can take 1 or 2 seconds, or not be done before a new action, or of course when you exit Lightroom.
We can assume that the modifications are made in a particular thread via a cache, but I don't think we can deactivate this cache.

**Comment by Rotbarde** [comment]
I took a closer look at the issue, I think it's because Lightroom or SQLite creates so-called "lrcat-wal" files (write ahead log) together with the ".lrcat" database and writes changes to this file first. Only when Lightroom has been inactive for some time or Lightroom is closed are the changes transferred to the actual "*.lrcat" database. I tried to trigger the process with an action in Lightroom, but unfortunately it didn't work.

**Comment by fdenivac** [comment]
Interesting, thank you. For my part, only working with Lightroom 6.14, this lrcat-wal file does not exist. On the other hand, I have an lrcat.journal, which grows regularly and is deleted when Lightroom is closed.
These 2 files are created by sqlite (https://sqlite.org/tempfiles.html).
